### ISSUE TITLE
`pueue show` when all jobs are finished

### ISSUE THREAD

**Issue by Yamakaky** [Nukesor/pueue#27]
After running `pueue show` without a running command:
```
Traceback (most recent call last):
  File "/usr/bin/pueue", line 11, in <module>
    load_entry_point('pueue==0.7.3', 'console_scripts', 'pueue')()
  File "/usr/lib/python3.6/site-packages/pueue/__init__.py", line 68, in main
    args.func(args_dict, root_dir)
  File "/usr/lib/python3.6/site-packages/pueue/client/displaying.py", line 148, in execute_show
    stdoutDescriptor = open(stdoutFile, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/yamakaky/.config/pueue/pueue_process_0.stdout'
```

**Comment by Nukesor** [comment]
Thanks for reporting! This will be fixed soon :+1:
