### ISSUE TITLE
Handle non utf-8 bytes in subprocess output

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#41]
If there are invalid characters in subprocess outputs, the daemon dies while he tries to parse and log the `stdout` and `stderr` output inside the `check_finished` function.
I'm just trying to reproduce this error and I'll add a stacktrace for later debugging.

**Comment by Nukesor** [comment]
```
Stdout output:

Traceback (most recent call last):
  File "/usr/bin/pueue", line 11, in <module>
    load_entry_point('pueue==0.8.6', 'console_scripts', 'pueue')()
  File "/usr/lib/python3.6/site-packages/pueue/__init__.py", line 68, in main
    args.func(args_dict, root_dir)
  File "/usr/lib/python3.6/site-packages/pueue/client/displaying.py", line 223, in execute_show
    print(stdoutDescriptor.read())
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 3803940: invalid start byte
```
